# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 28080
  servlet:
    context-path: /
    session:
      cookie:
        http-only: true

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: eb7b2ce065e17db46e06
#            client-secret: d3ac0aaaa03ccbcd6d5d191a5a471c315c1e9364

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: me.dwliu.ebase.demo.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ASSIGN_ID
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

#ebase:
#  swagger2:
#    docket:
#      aaa:
#        title: 测试
#        termsOfServiceUrl: http://blog.dwliu.me
#        base-package: me.dwliu.ebase.sample.controller
#        contact:
#          name: liudw
#          url: http://blog.dwliu.me/
#          email: liudw@qq.com
#        description: Starter for swagger 2.x
#        version: 1.0.0.RELEASE
#      bbb:
#        base-package: me.dwliu.ebase.demo.test.controller
#        title: 测试一下 bbb

